/**
 * Generate src/lib/generated/version.ts with the current Git commit SHA.
 *
 * This runs as a prebuild step so the /api/version endpoint can return
 * the exact commit SHA even outside Vercel (local dev, CI).
 *
 * On Vercel, VERCEL_GIT_COMMIT_SHA is already injected, but generating this
 * file ensures the SHA is always baked into the build output.
 */
import { execSync } from 'node:child_process'
import { writeFileSync, mkdirSync } from 'node:fs'

function getCommitSha(): string {
  // Vercel injects this at build time
  if (process.env.VERCEL_GIT_COMMIT_SHA) {
    return process.env.VERCEL_GIT_COMMIT_SHA
  }
  // Local dev: read from git
  try {
    return execSync('git rev-parse HEAD', { encoding: 'utf-8' }).trim()
  } catch {
    return 'unknown'
  }
}

function getBranch(): string {
  if (process.env.VERCEL_GIT_COMMIT_REF) {
    return process.env.VERCEL_GIT_COMMIT_REF
  }
  try {
    return execSync('git rev-parse --abbrev-ref HEAD', { encoding: 'utf-8' }).trim()
  } catch {
    return 'unknown'
  }
}

const sha = getCommitSha()
const branch = getBranch()
const buildTime = new Date().toISOString()

const content = `/**
 * AUTO-GENERATED by scripts/generate-version.ts — DO NOT EDIT.
 * Generated at build time with the current Git commit SHA.
 */
export const BUILD_COMMIT_SHA = ${JSON.stringify(sha)}
export const BUILD_BRANCH = ${JSON.stringify(branch)}
export const BUILD_TIME = ${JSON.stringify(buildTime)}
`

mkdirSync('src/lib/generated', { recursive: true })
writeFileSync('src/lib/generated/version.ts', content)

console.log(`✓ Generated src/lib/generated/version.ts — SHA: ${sha.substring(0, 7)} (${branch})`)
